import json

with open('e:/Projects/Garden App - Green Thumb/green-thumb/lib/plants.json', encoding='utf-8') as f:
    plants = json.load(f)

updates = {
    # VEGETABLES
    'amaranth':        {'growthHabit': 'upright'},
    'asparagus':       {'growthHabit': 'upright'},
    'bean_bush':       {'growthHabit': 'bush'},
    'bean_climbing':   {'growthHabit': 'climbing', 'trellisRequired': True},
    'beetroot':        {'growthHabit': 'rosette'},
    'bitter_melon':    {'growthHabit': 'vine',     'trellisRequired': True},
    'bok_choy':        {'growthHabit': 'rosette'},
    'broad_bean':      {'growthHabit': 'upright',  'trellisRequired': True},
    'broccoli':        {'growthHabit': 'upright'},
    'brussels_sprouts':{'growthHabit': 'upright'},
    'butternut_squash':{'growthHabit': 'vine'},
    'cabbage':         {'growthHabit': 'rosette'},
    'capsicum':        {'growthHabit': 'bush'},
    'carrot':          {'growthHabit': 'rosette'},
    'cassava':         {'growthHabit': 'upright'},
    'cauliflower':     {'growthHabit': 'rosette'},
    'celeriac':        {'growthHabit': 'rosette'},
    'celery':          {'growthHabit': 'upright'},
    'chickpea':        {'growthHabit': 'bush'},
    'chilli':          {'growthHabit': 'bush'},
    'choko':           {'growthHabit': 'vine',     'trellisRequired': True},
    'corn':            {'growthHabit': 'upright'},
    'cucumber':        {'growthHabit': 'vine',     'trellisRequired': True},
    'daikon':          {'growthHabit': 'rosette'},
    'edamame':         {'growthHabit': 'upright'},
    'eggplant':        {'growthHabit': 'upright'},
    'endive':          {'growthHabit': 'rosette'},
    'fennel_bulb':     {'growthHabit': 'upright'},
    'garlic':          {'growthHabit': 'upright'},
    'globe_artichoke': {'growthHabit': 'upright'},
    'jerusalem_artichoke': {'growthHabit': 'upright'},
    'kale':            {'growthHabit': 'upright'},
    'kangkong':        {'growthHabit': 'vine',     'trellisRequired': True},
    'kohlrabi':        {'growthHabit': 'rosette'},
    'leek':            {'growthHabit': 'upright'},
    'lettuce':         {'growthHabit': 'rosette'},
    'lupin':           {'growthHabit': 'upright'},
    'malabar_spinach': {'growthHabit': 'vine',     'trellisRequired': True},
    'mizuna':          {'growthHabit': 'rosette'},
    'mustard_greens':  {'growthHabit': 'rosette'},
    'oca':             {'growthHabit': 'spreading'},
    'okra':            {'growthHabit': 'upright'},
    'onion':           {'growthHabit': 'upright'},
    'pak_choy':        {'growthHabit': 'rosette'},
    'parsnip':         {'growthHabit': 'rosette'},
    'pea':             {'growthHabit': 'climbing', 'trellisRequired': True},
    'peanut':          {'growthHabit': 'spreading'},
    'popcorn':         {'growthHabit': 'upright'},
    'potato':          {'growthHabit': 'spreading'},
    'pumpkin':         {'growthHabit': 'vine'},
    'radicchio':       {'growthHabit': 'rosette'},
    'radish':          {'growthHabit': 'rosette'},
    'rainbow_chard':   {'growthHabit': 'upright'},
    'rocket':          {'growthHabit': 'rosette'},
    'rockmelon':       {'growthHabit': 'vine'},
    'shallot':         {'growthHabit': 'rosette'},
    'silverbeet':      {'growthHabit': 'upright'},
    'snow_pea':        {'growthHabit': 'climbing', 'trellisRequired': True},
    'spinach':         {'growthHabit': 'rosette'},
    'spring_onion':    {'growthHabit': 'upright'},
    'sugar_snap_pea':  {'growthHabit': 'climbing', 'trellisRequired': True},
    'swede':           {'growthHabit': 'rosette'},
    'sweet_potato':    {'growthHabit': 'vine'},
    'taro':            {'growthHabit': 'upright'},
    'tatsoi':          {'growthHabit': 'rosette'},
    'asian_greens_mix':{'growthHabit': 'rosette'},
    'tomatillo':       {'growthHabit': 'upright',  'trellisRequired': True},
    'tomato':          {'growthHabit': 'upright',  'trellisRequired': True},
    'cherry_tomato':   {'growthHabit': 'upright',  'trellisRequired': True},
    'turnip':          {'growthHabit': 'rosette'},
    'watercress':      {'growthHabit': 'spreading'},
    'watermelon':      {'growthHabit': 'vine'},
    'winged_bean':     {'growthHabit': 'climbing', 'trellisRequired': True},
    'witlof':          {'growthHabit': 'rosette'},
    'wombok':          {'growthHabit': 'rosette'},
    'yacon':           {'growthHabit': 'upright'},
    'zucchini':        {'growthHabit': 'bush'},
    # HERBS
    'basil':           {'growthHabit': 'bush'},
    'bay_laurel':      {'growthHabit': 'upright'},
    'chervil':         {'growthHabit': 'rosette'},
    'chives':          {'growthHabit': 'upright'},
    'coriander':       {'growthHabit': 'upright'},
    'curry_leaf':      {'growthHabit': 'upright'},
    'dill':            {'growthHabit': 'upright'},
    'fenugreek':       {'growthHabit': 'upright'},
    'galangal':        {'growthHabit': 'upright'},
    'ginger':          {'growthHabit': 'upright'},
    'horseradish':     {'growthHabit': 'upright'},
    'lavender':        {'growthHabit': 'bush'},
    'lemon_balm':      {'growthHabit': 'bush'},
    'lemon_myrtle':    {'growthHabit': 'upright'},
    'lemon_verbena':   {'growthHabit': 'bush'},
    'lemongrass':      {'growthHabit': 'upright'},
    'lovage':          {'growthHabit': 'upright'},
    'makrut_lime':     {'growthHabit': 'upright'},
    'marjoram':        {'growthHabit': 'spreading'},
    'mint':            {'growthHabit': 'spreading'},
    'nigella':         {'growthHabit': 'upright'},
    'oregano':         {'growthHabit': 'spreading'},
    'pandan':          {'growthHabit': 'upright'},
    'parsley':         {'growthHabit': 'rosette'},
    'perilla':         {'growthHabit': 'upright'},
    'rosemary':        {'growthHabit': 'bush'},
    'sage':            {'growthHabit': 'bush'},
    'sorrel':          {'growthHabit': 'rosette'},
    'stevia':          {'growthHabit': 'bush'},
    'summer_savory':   {'growthHabit': 'upright'},
    'tarragon':        {'growthHabit': 'upright'},
    'thai_basil':      {'growthHabit': 'bush'},
    'thyme':           {'growthHabit': 'spreading'},
    'turmeric':        {'growthHabit': 'upright'},
    'vietnamese_mint': {'growthHabit': 'spreading'},
    # FRUIT TREES
    'almond':          {'growthHabit': 'upright'},
    'apple':           {'growthHabit': 'upright'},
    'apricot':         {'growthHabit': 'upright'},
    'atemoya':         {'growthHabit': 'upright'},
    'avocado':         {'growthHabit': 'upright'},
    'babaco':          {'growthHabit': 'upright'},
    'banana':          {'growthHabit': 'upright'},
    'carambola':       {'growthHabit': 'upright'},
    'cherry':          {'growthHabit': 'upright'},
    'cumquat':         {'growthHabit': 'upright'},
    'feijoa':          {'growthHabit': 'upright'},
    'fig':             {'growthHabit': 'upright'},
    'grapefruit':      {'growthHabit': 'upright'},
    'jaboticaba':      {'growthHabit': 'upright'},
    'jujube':          {'growthHabit': 'upright'},
    'kiwifruit':       {'growthHabit': 'climbing', 'trellisRequired': True},
    'lemon':           {'growthHabit': 'upright'},
    'lime':            {'growthHabit': 'upright'},
    'loquat':          {'growthHabit': 'upright'},
    'lychee':          {'growthHabit': 'upright'},
    'macadamia':       {'growthHabit': 'upright'},
    'mandarin':        {'growthHabit': 'upright'},
    'mango':           {'growthHabit': 'upright'},
    'medlar':          {'growthHabit': 'upright'},
    'mulberry':        {'growthHabit': 'upright'},
    'nashi_pear':      {'growthHabit': 'upright'},
    'nectarine':       {'growthHabit': 'upright'},
    'olive':           {'growthHabit': 'upright'},
    'orange':          {'growthHabit': 'upright'},
    'passionfruit':    {'growthHabit': 'climbing', 'trellisRequired': True},
    'pawpaw':          {'growthHabit': 'upright'},
    'peach':           {'growthHabit': 'upright'},
    'pear':            {'growthHabit': 'upright'},
    'persimmon':       {'growthHabit': 'upright'},
    'plum':            {'growthHabit': 'upright'},
    'pomegranate':     {'growthHabit': 'upright'},
    'quince':          {'growthHabit': 'upright'},
    'tamarind':        {'growthHabit': 'upright'},
    'white_sapote':    {'growthHabit': 'upright'},
    'yuzu':            {'growthHabit': 'upright'},
    # BERRIES
    'acerola':         {'growthHabit': 'bush'},
    'strawberry_alpine':{'growthHabit': 'spreading'},
    'aronia':          {'growthHabit': 'bush'},
    'black_currant':   {'growthHabit': 'bush'},
    'blackberry':      {'growthHabit': 'climbing', 'trellisRequired': True},
    'blueberry':       {'growthHabit': 'bush'},
    'boysenberry':     {'growthHabit': 'climbing', 'trellisRequired': True},
    'cape_gooseberry': {'growthHabit': 'bush'},
    'chilean_guava':   {'growthHabit': 'bush'},
    'cranberry':       {'growthHabit': 'spreading'},
    'elderberry':      {'growthHabit': 'upright'},
    'goji_berry':      {'growthHabit': 'bush',     'trellisRequired': True},
    'gooseberry':      {'growthHabit': 'bush'},
    'grape_table':     {'growthHabit': 'climbing', 'trellisRequired': True},
    'grape_wine':      {'growthHabit': 'climbing', 'trellisRequired': True},
    'honeyberry':      {'growthHabit': 'bush'},
    'jostaberry':      {'growthHabit': 'bush'},
    'kiwi_berry':      {'growthHabit': 'climbing', 'trellisRequired': True},
    'lingonberry':     {'growthHabit': 'spreading'},
    'loganberry':      {'growthHabit': 'climbing', 'trellisRequired': True},
    'raspberry':       {'growthHabit': 'climbing', 'trellisRequired': True},
    'red_currant':     {'growthHabit': 'bush'},
    'thornless_rose':  {'growthHabit': 'bush'},
    'serviceberry':    {'growthHabit': 'upright'},
    'strawberry':      {'growthHabit': 'spreading'},
    'tayberry':        {'growthHabit': 'climbing', 'trellisRequired': True},
    'white_currant':   {'growthHabit': 'bush'},
    'youngberry':      {'growthHabit': 'climbing', 'trellisRequired': True},
    # NATIVES
    'bush_tomato':     {'growthHabit': 'bush'},
    'callistemon':     {'growthHabit': 'upright'},
    'davidson_plum':   {'growthHabit': 'upright'},
    'finger_lime':     {'growthHabit': 'upright'},
    'grevillea':       {'growthHabit': 'upright'},
    'kakadu_plum':     {'growthHabit': 'upright'},
    'kangaroo_paw':    {'growthHabit': 'upright'},
    'lemon_aspen':     {'growthHabit': 'upright'},
    'lilly_pilly':     {'growthHabit': 'upright'},
    'mountain_pepper': {'growthHabit': 'upright'},
    'muntries':        {'growthHabit': 'spreading'},
    'native_ginger':   {'growthHabit': 'upright'},
    'native_violet':   {'growthHabit': 'spreading'},
    'quandong':        {'growthHabit': 'upright'},
    'riberry':         {'growthHabit': 'upright'},
    'saltbush':        {'growthHabit': 'bush'},
    'warrigal_greens': {'growthHabit': 'spreading'},
    'wattleseed':      {'growthHabit': 'upright'},
    # PERENNIALS
    'artichoke':       {'growthHabit': 'upright'},
    'cardoon':         {'growthHabit': 'upright'},
    'comfrey':         {'growthHabit': 'upright'},
    'good_king_henry': {'growthHabit': 'upright'},
    'rhubarb':         {'growthHabit': 'upright'},
    'sea_kale':        {'growthHabit': 'upright'},
    'walking_onion':   {'growthHabit': 'upright'},
    # FLOWERS
    'agapanthus':      {'growthHabit': 'upright'},
    'cosmos':          {'growthHabit': 'upright'},
    'dahlia':          {'growthHabit': 'upright'},
    'marigold':        {'growthHabit': 'bush'},
    'salvia_ornamental':{'growthHabit': 'upright'},
    'statice':         {'growthHabit': 'upright'},
    'sunflower':       {'growthHabit': 'upright'},
    'zinnia':          {'growthHabit': 'upright'},
    # EDIBLE FLOWERS
    'bee_balm':        {'growthHabit': 'upright'},
    'borage':          {'growthHabit': 'upright'},
    'calendula':       {'growthHabit': 'upright'},
    'chamomile':       {'growthHabit': 'spreading'},
    'chamomile_roman': {'growthHabit': 'spreading'},
    'chive_flowers':   {'growthHabit': 'upright'},
    'dianthus':        {'growthHabit': 'bush'},
    'elderflower':     {'growthHabit': 'upright'},
    'nasturtium':      {'growthHabit': 'spreading'},
    'pansies_edible':  {'growthHabit': 'spreading'},
    'hibiscus_roselle':{'growthHabit': 'upright'},
    'sweet_violet':    {'growthHabit': 'spreading'},
    'viola':           {'growthHabit': 'spreading'},
    # COTTAGE
    'aquilegia':       {'growthHabit': 'upright'},
    'alyssum':         {'growthHabit': 'spreading'},
    'delphinium':      {'growthHabit': 'upright',  'trellisRequired': True},
    'echinacea':       {'growthHabit': 'upright'},
    'forget_me_not':   {'growthHabit': 'spreading'},
    'foxglove':        {'growthHabit': 'upright'},
    'gypsophila':      {'growthHabit': 'spreading'},
    'hollyhock':       {'growthHabit': 'upright',  'trellisRequired': True},
    'rose_heritage':   {'growthHabit': 'bush',     'trellisRequired': True},
    'scabiosa':        {'growthHabit': 'upright'},
    'snapdragon':      {'growthHabit': 'upright'},
    'stock':           {'growthHabit': 'upright'},
    'sweet_pea':       {'growthHabit': 'climbing', 'trellisRequired': True},
    'sweet_william':   {'growthHabit': 'upright'},
    'wallflower':      {'growthHabit': 'bush'},
}

updated = 0
not_found = []
for plant in plants:
    pid = plant['id']
    if pid in updates:
        for k, v in updates[pid].items():
            plant[k] = v
        updated += 1
    elif not plant.get('growthHabit'):
        not_found.append(pid)

with open('e:/Projects/Garden App - Green Thumb/green-thumb/lib/plants.json', 'w', encoding='utf-8') as f:
    json.dump(plants, f, ensure_ascii=False, indent=2)

print(f'Updated: {updated}')
if not_found:
    print(f'Still missing growthHabit: {not_found}')
else:
    print('All plants have growthHabit!')

from collections import Counter
habits = Counter(p.get('growthHabit', 'none') for p in plants)
trellis = sum(1 for p in plants if p.get('trellisRequired'))
print('Habit breakdown:', dict(habits))
print(f'Needs support: {trellis} plants')
